name: Terraform Validation

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: [self-hosted, platform-runner]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform version
        run: terraform version

      - name: Google Cloud CLI Version
        run: gcloud version

      - name: Terraform fmt
        run: terraform -chdir=terraform fmt -check -recursive

      - name: Terraform init
        run: terraform -chdir=terraform init

      - name: Terraform validate
        run: terraform -chdir=terraform validate