name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: [self-hosted, platform-runner]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/75857734333/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: terraform-deployer@project-ff80b6ff-8c4e-4127-89e.iam.gserviceaccount.com

      - name: Terraform init
        run: terraform -chdir=terraform init

      - name: Terraform apply
        run: terraform -chdir=terraform apply -auto-approve