name: Terraform Validation

on:
  push:

jobs:
  validate:
    runs-on: [self-hosted, platform-runner]

    steps:
      - uses: actions/checkout@v4

      - name: Show Runner Info
        run: |
          echo "Runner is working"
          whoami
          pwd
          hostname

      - name: Terraform Version
        run: terraform version

      - name: Python Version
        run: python3 --version

      - name: Git Version
        run: git --version